version: "3.8"
services:
  backend:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - cache
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
